### ISSUE TITLE
Add CentOS compatibilty and TK tests

### ISSUE THREAD

**Issue by BarthV** [BarthV/sinopia-cookbook#6]

**Comment by swalberg** [comment]
I'm trying this on a CentOS 6.5 box and the main problem seems to be the init script. The machine has upstart-0.6.5-12.el6_4.1.x86_64 but it won't start the service. I'm getting an `unknown stanza` error on the setgid/setuid lines, as that's not supported until later versions.

**Comment by BarthV** [comment]
I didn't touch this cookbook for a long time, but I can accept & test every PR submitted to the repo.
Maybe we should make a global upgrade and support other init system for sure.

I'll take some time to see if i can implement any "daemonizer".

**Comment by swalberg** [comment]
I'm looking into a sysv init script today...
